# Generated by Django 4.1.7 on 2023-07-18 19:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_post_options_alter_school_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='school',
            options={},
        ),
        migrations.AlterField(
            model_name='school',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userc',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='main.school'),
        ),
    ]
