# Generated by Django 4.1.7 on 2023-07-19 04:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_school_options_alter_school_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='postsdeposts', to='main.school'),
        ),
        migrations.AlterField(
            model_name='userc',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usersdeusers', to='main.school'),
        ),
    ]
